name: FreePC Telegram Bot

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          pip install pyTelegramBotAPI requests

      - name: Start Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python bot.py
